# Generated by Django 3.2.9 on 2021-11-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('texts', models.TextField()),
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('replied_user_name', models.CharField(default='None', max_length=125)),
                ('game', models.ForeignKey(default=567, on_delete=django.db.models.deletion.CASCADE, to='chat.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
